import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docs: [
    {
      type: "doc",
      id: "index",
      label: "What do you want to do?",
    },
    {
      type: "category",
      label: "Getting Started",
      collapsed: false,
      link: { type: "generated-index", slug: "/getting-started" },
      items: [
        "getting-started/try-stave",
        "getting-started/first-evaluation",
        "getting-started/installation",
        "getting-started/reading-chain-findings",
        "getting-started/first-finding",
        "getting-started/fix-and-verify",
        "getting-started/add-to-ci",
      ],
    },
    {
      type: "category",
      label: "Labs",
      link: { type: "doc", id: "labs/index" },
      items: [
        {
          type: "category",
          label: "S3",
          items: [
            "labs/s3-public-exposure-long-lived-iam-keys",
            "labs/s3-ransomware-protection-forensic-auditability",
          ],
        },
        {
          type: "category",
          label: "IAM",
          items: [
            "labs/shadow-admin-compute-role-privilege-drift",
            "labs/cross-account-kms-key-policy-isolation",
          ],
        },
        {
          type: "category",
          label: "Cognito",
          items: ["labs/cognito-unauthenticated-s3-takeover"],
        },
        {
          type: "category",
          label: "Multi-Service",
          items: [
            "labs/sadcloud-multi-service-validation",
            "labs/chain-discovery",
          ],
        },
        {
          type: "category",
          label: "Lambda MicroVM",
          link: {
            type: "generated-index",
            slug: "/labs/lambda-microvm",
            title: "Lambda MicroVM Security Labs",
            description:
              "Eight self-contained labs for the Lambda MicroVM control family.",
          },
          items: [
            "labs/lambda-microvm/baseline-compliant-microvm",
            "labs/lambda-microvm/overprivileged-execution-role",
            "labs/lambda-microvm/missing-tagsession",
            "labs/lambda-microvm/03b-overbroad-tagsession",
            "labs/lambda-microvm/compound-path",
            "labs/lambda-microvm/public-artifact-bucket",
            "labs/lambda-microvm/excessive-idle-runtime",
            "labs/lambda-microvm/secrets-in-snapshot",
          ],
        },
        {
          type: "category",
          label: "Advanced",
          items: [
            "labs/reasoning-engines",
            "labs/lab-metrics",
            "labs/library-in-process",
            "labs/policy-forge",
            "labs/logic-trace",
            "labs/writing-controls",
            "labs/compliance-evidence",
          ],
        },
        {
          type: "category",
          label: "Skill Track",
          link: { type: "doc", id: "labs/skill-track/index" },
          items: [
            "labs/skill-track/build-and-verify",
            "labs/skill-track/first-findings",
            "labs/skill-track/lab-validation",
            "labs/skill-track/write-a-control",
            "labs/skill-track/reasoning-engines",
            "labs/skill-track/snapshot-your-account",
          ],
        },
        {
          type: "category",
          label: "Data Import",
          items: [
            "labs/from-steampipe-to-stave",
            "labs/docker-demo",
          ],
        },
        {
          type: "category",
          label: "Docker Scenarios",
          link: {
            type: "generated-index",
            slug: "/labs/docker-scenarios",
          },
          items: [
            { type: "autogenerated", dirName: "labs/docker-scenarios" },
          ],
        },
        {
          type: "category",
          label: "HackerOne Case Studies",
          link: { type: "doc", id: "labs/case-studies/index" },
          items: [
            "labs/hackerone",
            "labs/case-studies-setup",
            "labs/case-study-questions",
            "labs/now-run-stave",
            "labs/case-studies-debrief",
            {
              type: "category",
              label: "Public Exposure",
              items: [
                "labs/case-studies/uber-361438",
                "labs/case-studies/slack-404822",
                "labs/case-studies/shopify-1021906",
                "labs/case-studies/omise-1474017",
                "labs/case-studies/zomato-507097",
                "labs/case-studies/shopify-57505",
                "labs/case-studies/greenhouse-819278",
                "labs/case-studies/shopify-94502",
                "labs/case-studies/mapbox-202725",
                "labs/case-studies/mozilla-2383486",
                "labs/case-studies/hackerone-43280",
              ],
            },
            {
              type: "category",
              label: "Dangling References & Takeover",
              items: [
                "labs/case-studies/bime-121461",
                "labs/case-studies/dod-918946",
                "labs/case-studies/khanacademy-1777077",
                "labs/case-studies/tendermint-1397826",
                "labs/case-studies/brave-1791558",
                "labs/case-studies/shopify-1295497",
                "labs/case-studies/brave-1835133",
                "labs/case-studies/hackerone-1598347",
                "labs/case-studies/ibm-2498255",
              ],
            },
            {
              type: "category",
              label: "Presigned URL & Policy Scope",
              items: [
                "labs/case-studies/unikrn-254200",
                "labs/case-studies/shopify-93691",
                "labs/case-studies/bcm-764243",
                "labs/case-studies/shopify-94087",
              ],
            },
            {
              type: "category",
              label: "Compound & Cross-Service",
              items: [
                "labs/case-studies/dod-2083771",
                "labs/case-studies/shopify-98819",
                "labs/case-studies/kubernetes-1580493",
                "labs/case-studies/aws-3021451",
                "labs/case-studies/aws-3022516",
                "labs/case-studies/kubernetes-1238482",
              ],
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "How-to Guides",
      link: { type: "generated-index", slug: "/how-to" },
      items: [{ type: "autogenerated", dirName: "how-to" }],
    },
    {
      type: "category",
      label: "Reference",
      link: { type: "generated-index", slug: "/reference" },
      items: [
        {
          type: "category",
          label: "Schemas & Contracts",
          items: [
            "reference/contracts",
            "reference/schema-obs",
            "reference/schema-out",
            "reference/schema-ctrl",
            "reference/schema-diagnose",
            "reference/schema",
            "reference/observation-contract",
            "reference/observation-export-schema",
            "reference/operator-contract",
            "reference/evidence-packet-spec",
            "reference/exempt-spec",
            "reference/stability",
          ],
        },
        {
          type: "category",
          label: "CLI",
          items: [
            { type: "autogenerated", dirName: "reference/cli-reference" },
            "reference/config-file",
          ],
        },
        {
          type: "category",
          label: "Evaluation",
          items: [
            "reference/evaluation-semantics",
            "reference/cel-predicates",
            "reference/evaluation-engine-capabilities",
            "reference/fact-export",
          ],
        },
        {
          type: "category",
          label: "Output",
          items: [
            "reference/output-formats",
            "reference/output-and-severity",
            "reference/severity-thresholds",
          ],
        },
        {
          type: "category",
          label: "Controls",
          items: [
            {
              type: "autogenerated",
              dirName: "reference/invariants-reference",
            },
            "reference/identity-blast-radius",
          ],
        },
        {
          type: "category",
          label: "Compliance Mappings",
          items: [
            "reference/compliance-owasp-nhi",
            "reference/hipaa-table",
            "reference/hipaa-cli",
          ],
        },
        {
          type: "category",
          label: "Integrations",
          items: [
            "reference/integration-guide",
            "reference/baseline-action",
            "reference/graph-libraries",
            {
              type: "autogenerated",
              dirName: "reference/integrations",
            },
          ],
        },
        {
          type: "category",
          label: "Project",
          items: [
            "reference/changelog",
            "reference/glossary",
            "reference/scope-and-support",
            "reference/security-policy",
            "reference/iam-permissions",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Explanation",
      link: { type: "generated-index", slug: "/explanation" },
      items: [
        {
          type: "category",
          label: "How Stave Works",
          collapsed: false,
          items: [
            "explanation/how-stave-works",
            "explanation/snapshot-model",
            "explanation/controls-as-code",
            "explanation/architecture",
            "explanation/data-flow",
            "explanation/files-as-the-boundary",
            "explanation/design-philosophy",
            "explanation/logic-trace",
          ],
        },
        {
          type: "category",
          label: "Security & Trust",
          items: [
            "explanation/guarantees",
            "explanation/threat-model",
            "explanation/trust-and-security",
            "explanation/execution-safety",
            "explanation/release-security",
            "explanation/air-gapped-analysis",
          ],
        },
        {
          type: "category",
          label: "Reasoning Engines & Verification",
          items: [
            "explanation/system-invariants",
            "explanation/reasoning-contract",
            "explanation/z3-solver",
            "explanation/z3-question-catalogue",
          ],
        },
        {
          type: "category",
          label: "Compound Risk Analysis",
          items: [
            "explanation/compound-chains",
            "explanation/chain-discovery-architecture",
            "explanation/blast-radius",
            "explanation/identity-blast-radius",
            "explanation/secret-blast-radius",
          ],
        },
        {
          type: "category",
          label: "Attack Path Analysis",
          items: [
            "explanation/data-exfiltration",
            "explanation/unauthenticated-reachability",
            "explanation/shadow-logic",
            "explanation/entitlement-entropy",
            "explanation/supply-chain-ingress",
            "explanation/kms-concentration",
            "explanation/vendor-trust-leash",
            "explanation/temporal-ghost",
          ],
        },
        {
          type: "category",
          label: "Assessment & Evidence",
          items: [
            "explanation/evidence-bundling",
            "explanation/evidence-driven-design",
            "explanation/posture-score",
            "explanation/posture-trending",
            "explanation/counterfactual-analysis",
          ],
        },
        {
          type: "category",
          label: "Operational Concepts",
          items: [
            "explanation/drift-detection",
            "explanation/time-travel",
            "explanation/recovery-isolation",
            "explanation/data-sovereignty",
          ],
        },
        {
          type: "category",
          label: "FAQ & Differentiation",
          items: [
            "explanation/differentiation",
            "explanation/faq",
            "explanation/vs-scanners",
            "explanation/vs-vulnerable-labs",
            "explanation/lab-results",
          ],
        },
      ],
    },
  ],
};

export default sidebars;
